export const TASKS_FETCH = 'TASKS_FETCH'
export const TASKS_CHANGE_PAGE = 'TASKS_CHANGE_PAGE'
export const TASKS_CHANGE_FILTER = 'TASKS_CHANGE_FILTER'
export const TASKS_CHANGE_DIRECTION = 'TASKS_CHANGE_DIRECTION'

export const TASK_ADD = 'TASK_ADD'
export const TASK_EDIT = 'TASK_EDIT'

export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'
